configured_endpoints: 116
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/metronome/metronome-d87fdcf132d47fbb50c29b6289f16afafe3ca5d4894e12e578bf8ffd4f7e745a.yml
openapi_spec_hash: 3d664dbba8e855b1f09edfcbd154cae9
config_hash: 82cceaeee1ce998c3e1aa0e082a4629e
